### ISSUE TITLE
Understanding how plush works

### ISSUE THREAD

**Issue by Maaarcocr** [zetavm/zetavm#20]
So I'm trying to add float support to plush mainly to be able to test floats in a higher level language. 
Now, I'm not fully sure about how the front end for plush works. 
My main point of confusion is the fact that the parser has some parts written in cpp and others in plush.
Moreover, the runtime is written in plush but the code generation in cpp. 

So the runtime.pls is firstly interpreted and it seems that it adds support to overloaded symbols, such as +

The code generation in cpp produces .zim code and when it encounters an overloaded symbol it uses functions defined in runtime

What about parser.pls? Is it ever used?

**Comment by maximecb** [comment]
The reason it might be confusing is that there are two plush implementations. There is a C++ implementation (parser.cpp, codegen.cpp, etc), and there is also a plush-written-in-plush implementation (parser.pls). The runtime.pls file is, as you pointed out, used to define certain symbols. It also implements the behavior of primitive operators in plush (what happens when you do x + y). Both implementations make use of it.

When you compile a file with cplush (the C++ implementation), it gives you a standalone zim file. Now, cplush is used to compile parser.pls into packages/lang/plush/0/package.

You might be wondering why this is useful. The reason is, once we have a compiled parser package, Zeta has support for plush. When you run a source file with a line that says `#language "lang/plush/0" at the top, it's telling ZetaVM to load this parser package and use this to parse the source code found in the file.

Eventually, Zeta will have a package manager, and people will be able to upload packages that implement parsing/codegen for their own languages... And by doing that, they will be giving everyone instant access to their new language in a way that will feel native. What's more is that code written in plush will be able to import code written in any other language supported by ZetaVM. That is a big part of my "grand plan". 

Back to the original problem. The C++ Plush implementation is more bare-bones and less user-friendly. I created it so that I would have a tool to write the self-hosted code with, but it only has to have just enough features. It doesn't support the "import" statement, for example. Eventually, I might like for parser.pls to replace the C++ implementation, but at this stage, I think it's wise to keep the C++ implementation in working order... If only because it gives people an example of how to write a standalone compiler, in a language that they are likely to be familiar with.

You could add FP support to either the C++ or the self-hosted parser.pls implementation. It might make more sense to implement it in parser.pls, but I understand if you find that confusing and would prefer to write C++. If you want, you can do C++ support and I can write the parser.pls version. I will let you choose :)

**Comment by Maaarcocr** [comment]
I'll try to implement floats in the plush version! 
I'll try my best to have it ready as soon as possible, but till Wednesday I'm a different conferences so I'll be a bit busy. 
Thanks for the clarification.

**Comment by maximecb** [comment]
@Maaarcocr No problem. Deep learning talks at work for me today.

I did make some changes since your last PR. I changed the int type to int32. Make sure to do a `git pull` when you look at the code again.

Enjoy the conferences :)

**Comment by Maaarcocr** [comment]
Small update: 
I'm sorry, but I'm actually going to implement is in c++. I just find it easier to implement it due to the presence of atof. 
I may actually implement floats into the c++ one, so that I can use str_to_f32 in the plush integration later on. 
I hope that my change of mind doesn't cause any problem.

**Comment by maximecb** [comment]
Sure, no problem. This project is meant to be fun too :)

**Comment by Maaarcocr** [comment]
It is fun :) I'm learning a good amount of things, thanks!
