### ISSUE TITLE
Missing math library features

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#38]
I was working on code to do sound/music generation the other day, and I'm missing a few features that probably should be in our math library (plush/math.pls).

It would be useful to have functions such as `floor`, `ceil`, `round` and `fmod`, which work as in the C library. I believe it should be possible to implement these without introducing new instructions in the VM. The functions should be tested with negative, positive, zero and other integer values to make sure there are no edge cases.

EDIT: @tommyettinger points out that we also may want to add a `math.isNaN(x)` function, and an infinity constant, `math.INFINITY`.

EDIT 2017-06-21: math.INF, math.isNaN, math.floor and math.fmod are now done

**Comment by tommyettinger** [comment]
Are they defined for (the many possible values of) NaN? Should Zeta just react to any NaN appearing with an exception? I know there are cases where it's a reasonable value that can occur and may need handling, I believe mainly in various matrix math things. There's a lot of weird things with NaN though, like the trick used to puzzle newcomers to the Clojure language (often to annoy trolls) where someone creates a set of 3 "unique", guaranteed-not-equal items, `NaN`, `NaN`, and `NaN`. With each NaN created in a different way, each carries a different object reference, and because of how NaN is value-unequal to NaN, neither reference nor value equality can tell the NaNs are the same. There's also the much more-relevant issue of positive and negative infinity, which make total sense for max and min to support, but not as much for floor and ceil. In general, if NaN and infinities are present, you also need some math package functions to tell if something is NaN and to tell if something is infinite.

**Comment by maximecb** [comment]
I was thinking that to maximize performance (by avoiding dynamic checks) we would use the same semantics as C when it comes to NaN, that is, if you feed NaN into the input, you get NaN as output.

You can test for NaN, by checking that a value is not equal to itself. That being said, I'm in favor of adding an isNaN function, and an infinity constant.
