### ISSUE TITLE
Travis being slow.

### ISSUE THREAD

**Issue by Maaarcocr** [zetavm/zetavm#51]
Today, just to start building 2 PRs ( #49 #50 )  travis took almost 3 hours, and this is not the first problem it gives us (when we moved repo it stopped building). Ideally we would like to have our CI to be as stable and fast as possible. 
Should we try CircleCI? I could try to set it up in my repo and then for a first period we could have both CIs testing our code to see which one is the best one. 
In the meanwhile I could also integrate AppVeyor (https://www.appveyor.com/) that will allow us to build and test on Windows!

**Comment by maximecb** [comment]
I'm open to it. The best would really be to use a service that has linux, windows and macos machines.

**Comment by Maaarcocr** [comment]
As far as I know there is no such thing :( Most services have Linux + MacOS. 
AppVeyor is the only one that has Windows, but they only do that. 
I guess the best option is to have one service for Linux and MacOS and AppVeyor for Windows.

I'll try out Circle to check if they have a decent version of gcc and if we can run MacOS tests there.

**Comment by tommyettinger** [comment]
I'm not sure how AppVeyor works, but I should mention that I've only run the build and tests using Cygwin, and there are various alternatives to Cygwin that might be preferable on their CI service. Cygwin makes various changes to how paths work while in a Cygwin Bash shell, to try to let Unix-based applications run with minimal changes. I'll see if I can run GNU Make and build ZetaVM from a normal, highly-limited `cmd.exe` session, but I'm not especially optimistic because `cmd.exe` doesn't even run software meant for Windows very well.. If cmd works, then that should mean AppVeyor would have no prerequisites for the build other than GCC or Clang and the various GNU tools for building. It might even build with the MS tools for C++, but those can have all sorts of issues with compatibility.

**Comment by maximecb** [comment]
@Maaarcocr Trying to enable appveyor on zetavm... Yay it worked 👍

**Comment by maximecb** [comment]
Closing this for now.
