### ISSUE TITLE
Command-line argument parsing

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#55]
I think that we will eventually need to have command-line argument parsing for ZetaVM. This will be needed in order to set various parameters (eg: to disable the JIT compiler, or set the initial heap memory size). I'm kind of allergic to external dependencies, so I would rather we roll our own.

I kind of like the way V8 does it, which is a syntax of the form:

```
zeta --option_name=<option_value> --opt2=<val2> <program_file> -- <prog_arg0> ... <prog_argn>
```

For example:

```
zeta --nojit --init_heap_size=2048 sumthenumbers.pls -- 1 2 3
```

The arguments past the double-dash `--` are stored in an array and passed to the running program's main function.

**Comment by ashwanidausodia** [comment]
Anybody working on this???

**Comment by maximecb** [comment]
Noone is working on it. You're welcome to take a stab at it 👍  :)

**Comment by ashwanidausodia** [comment]
#### Regarding the design
There can be a header-only implementation of the Parser. It can take a list of expected arg options and user provided arguments.

You can declare expected arg option as
```cpp
Arg option{'i', "init_heap_size", INT}
```
or, If type is bool and short name is not there. 
```cpp
Arg option{"nojit", BOOL};
```
Also type can be omited if it is BOOL. Then, create a parser and tell it to parse.
```cpp
ArgParser parser{argOptions};
parser.parse(argc, argv);
```
And then you can query like
```cpp
parser.isPresent('nojit')            // returns true
parser.get("init_heap_size")         // 2048 as string
parser.getAsInt("init_heap_size")    // 2048 as int
```
also
```cpp
parser.getProgramName();
parser.getProgramArgc();
parser.getProgramArgv();
```
I was thinking that `parser.parse` function should throw exception if user specifies an option which is not expected or expected with different type of value. E.g passing a non-number to init_heap_size or passing `--foobar` would result in such exception.

Also if you ask for
```cpp
parser.get("init_heap_size")
```
It can throw exception if `--init_heap_size` is not passed as an argument. In that case every call to `get` or `getAsInt` should be preceded by `isPresent`. Or instead of throwing an exception we can also wrap return value in an `Optional` type, which will be empty if `--init_heap_size` is not passed as an argument.

Share your thoughts on this.

**Comment by maximecb** [comment]
I like your design overall. I would declare the options in `main.cpp` if possible, because that seems like the most sensible place.

Regarding the use of initializer lists:

```
Arg option{'i', "init_heap_size", INT}
```

It might actually work better if you use optional arguments to a constructor, because for integers, we may want to have things like minimum and maximum allowable values, which are going to be optional. Otherwise, at the very least, we will want to differentiate int from strictly non-negative int.

```
It can throw exception if --init_heap_size is not passed as an argument. In that case every call to get or getAsInt should be preceded by isPresent
```

Seems a bit burdensome to have to call isPresent on everything. IMO, most arguments are going to be optional, so the arguments need to have default values which are returned if nothing is specified. Could still have an `isPresent()` method to check if a value was actually provided or not.

Another thing is, we might end up having lots of options. When we begin implementing a JIT compiler, we will have all sorts of options to tweak the way the compiler optimizes code. Ideally, these could be directly mapped to global variables somewhere. What I'm saying is, it could quickly become very burdensome to have to extract each option manually from the `parser`. It would be great if we could tell the parser to store the value of this option in the global variable named `jitMaxCodeSize` or `jitEnableInlining`, which is defined in some header somewhere.

**Comment by ashwanidausodia** [comment]
>IMO, most arguments are going to be optional, so the arguments need to have default values which are returned if nothing is specified

>we might end up having lots of options. When we begin implementing a JIT compiler, we will have all sorts of options to tweak the way the compiler optimizes code. Ideally, these could be directly mapped to global variables somewhere

>we may want to have things like minimum and maximum allowable values

Based on these three points I have tweaked the design a little bit. Since, we may have to validate the value (e.g. minimum and maximum allowable values), the validation has to be moved out of parser. It will also make parser more generic.

Now you can declare arg as

`Arg option{'i', "init_heap_size", handler)`

Unlike earlier you don't have to tell the type of arg but you have to provide a `handler`, which is a callback and will be called when parser parses the argument `--init_heap_size`. It is `handler`'s responsibility to validate and store the value. `handler` is a function of signature `void handler (bool, string)`. `bool` indicates if value was present for that option and `string` is the actual value. `bool` is needed because boolean arguments like `enable_jit` do not expect a value. You should not say `--enable_jit=<some_value>`.

Parser can provide common handler's like
1. Int / Non negative int
2. Int / Non negative int with range check
3. String / Non empty String
4. Booleans


With this you could declare options like

```cpp
// Global data structure for all options
struct Options {
  uint init_heap_size = 1024;
  bool enable_jit = false;
  int some_option;
  std::string some_other_option = "foobar"; // default value
} opts;

ArgParser parser = ArgParser(
  Arg('-i', "init_heap_size", get_uint_handler(opts.init_heap_size)),
  Arg("enable_jit", get_bool_handler(opts.enable_jit),
  Arg('-s', "some_option", get_int_handler(opts.some_options)),
  Arg("some_other_option", some_other_value_handler)
);

void some_other_value_handler(bool is_value_present, std::string value) {
  if (!is_value_present) {
    throw ParseException("some_other_option expects a value");
  }
  // Validate other things about value and then update the value
  
  opt.some_other_option = value;
  // default value will be overridden iff  user provided this argument and value was valid
}
```

`get_uint_handler`,  `get_bool_handler` and `get_int_handler` are functions provided by parser which return a handler which validates the value and stores it in the provided argument. This satisfies all three requirements : default values, store in global data structure and validation.

**Comment by maximecb** [comment]
Seems fairly good. I see two weak points:

1. This design makes it possible to forget to initialize values. Most values are going to be optional, so we should probably make the handlers require a default value.

2. The arg parser has no knowledge of what types the values have, or what their default values are. This is going to be a problem if we want to auto-generate `--help` output.

I think it might be simpler if we simply declared arguments like this:

```
BoolArg enable_jit(true, "enable the JIT compiler");
UIntArg init_heap_size(1024, "initial GC heap size");
```

You could override `operator bool ()` to tell if the arguments are present or not, and have a `get ()` function to get the value, or override the dereference operator for that.

We could declare these in a `options.h` header as well, or specifically where they are needed (eg: `jit.cpp`). The arguments could auto-add themselves to the argument parser.

**Comment by maximecb** [comment]
Well done @ashwanidausodia 

Is your parser currently able to handle program arguments too?

ie: extracting args after the `--` in:

```
zeta --nojit --init_heap_size=2048 sumthenumbers.pls -- 1 2 3
```

These arguments should be placed in an std::vector so that we can pass them to the running program.

**Comment by ashwanidausodia** [comment]
Yes it does, You can call `getProgramArgc()` and `getprogramArgv()` functions on OptParser().
For this example.
 ```
zeta --nojit --init_heap_size=2048 sumthenumbers.pls -- 1 2 3
```
`getProgramArgc()` will return 3
`getProgramArgv()` will return a char*[]
I forgot to write test case for these. I'll add them.

**Comment by maximecb** [comment]
Hi @ashwanidausodia 

I'm working on adding support for program arguments to ZetaVM. I'm finding the current interface with `getProgramArgc` and `getProgramArgv` kind of cumbersome. Could you instead implement a `getProgramArgs` which returns an `std::vector<std::string>` ?

**Comment by maximecb** [comment]
Tadaaaaa: https://github.com/zetavm/zetavm/commit/1ea056773cbae35017ec3b82d3e3bad00c8e5f8b

:+1:

**Comment by maximecb** [comment]
@ashwanidausodia Thanks for making this change. I think the next step, if/when you have time, would be to generate `--help` usage information.

**Comment by ashwanidausodia** [comment]
Yes, short name is optional

**Comment by maximecb** [comment]
@ashwanidausodia Would you have time to implement `--help` with generated program usage information?

**Comment by ashwanidausodia** [comment]
This week I am busy. Maybe weekend

**Comment by maximecb** [comment]
Ok no problem. I appreciate the work you've done so far :)

**Comment by maximecb** [comment]
Will close this issue for now. I think the implementation by @ashwanidausodia satisfies all the requirements for the moment being 👍
