### ISSUE TITLE
Implement "A Little Smalltalk"

### ISSUE THREAD

**Issue by pgregory** [zetavm/zetavm#72]
I'd like to explore creating a version of Tim Budd's "A Little Smalltalk" on top of ZetaVM, perhaps as a precursor to a more fully featured Smalltalk.

**Comment by maximecb** [comment]
That would be cool. I like minimalist languages. Do you have any questions about ZetaVM and which direction to go in to implement certain features?

**Comment by pgregory** [comment]
I'm looking through the code at the moment, getting familiar with it. 

I have plenty of experience with LST, so just need to work out how to transfer my existing knowledge of parsing LST syntax into Zeta. Once I've done that, I'm not clear at the moment how best to implement the standard library, but that can wait.

One question, would you recommend C/C++ or Plush as the best option for generating the zim file?

**Comment by maximecb** [comment]
That probably depends on your level of comfort.

The self-hosted Plush parser, what I call the Plush language package (plush/parser.pls) generates code directly in memory. I think that eventually, this is the way every language should be implemented on Zeta. It makes it easy to implement a REPL, or things like eval.

The downside is that Plush and the way parser.pls is structured are still in flux. For instance, I want to move some parser code from parser.pls into its own std/parsing package. Specifically, I want to move out the Input object, and functions to do things like parsing numbers and string literals, so that this code can be reused by other implementations.

**Comment by pgregory** [comment]
"Comfort" doesn't come into it, what's life without an adventure? :) 

I'll investigate the Plush method and see if I can get my head round it. Thankfully the LST syntax is very simple, so shouldn't be too challenging.

**Comment by maximecb** [comment]
Good. Then I encourage you to write your parser in Plush, in the manner that `parser.pls` is written. This will ultimately make it possible to upload your Smalltalk parser to the Zeta package manager, and give "native" Smalltalk support to Zeta, by adding a `#language lang/smalltalk/0` line to the beginning of source files.

Speaking of which, do you have a name your package would go by? How about `littletalk` ?

**Comment by pgregory** [comment]
littletalk works.

**Comment by maximecb** [comment]
I started moving some of the parsing functions into their own library, so people can reuse them: https://github.com/zetavm/zetavm/blob/79d3c8325e5678d7e4fc87e251c6abec2f7426d5/plush/parsing.pls
